const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Fit pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Slim pants',
      slug: 'slim-pants',
      category: 'Pants',
      image: '/images/pants3.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
